spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${APP_SERVERNAME:localhost}:${APP_SERVERPORT:5432}/${APP_DBNAME:postgres}
    username: ${APP_USERNAME:postgres}
    password: ${APP_SECRET:postgres}
    initialization-mode: always

logging:
  level:
    sql: error
    org: error
    com: error
    ru: error
